In [1]:
import numpy as np

In [3]:
a = np.zeros((2,2))

In [4]:
b = np.ones((2,2))

In [5]:
a

array([[0., 0.],
       [0., 0.]])

In [6]:
b

array([[1., 1.],
       [1., 1.]])

In [8]:
np.sum(a,axis=1)

array([0., 0.])

In [9]:
np.sum(b,axis=1)

array([2., 2.])

In [13]:
c = np.arange(4)

In [18]:
np.array(c)

array([0, 1, 2, 3])

In [22]:
d = c.reshape((2,2))

In [23]:
d

array([[0, 1],
       [2, 3]])

In [24]:
np.sum(d,axis = 1)

array([1, 5])

In [25]:
np.sum(d, axis = 0)

array([2, 4])

In [26]:
np.reshape(c,(2,2))

array([[0, 1],
       [2, 3]])

In [27]:
c

array([0, 1, 2, 3])

In [28]:
b * 5 + 1

array([[6., 6.],
       [6., 6.]])

In [29]:
np.dot(a,b)

array([[0., 0.],
       [0., 0.]])

In [32]:
np.dot(b,d)

array([[2., 4.],
       [2., 4.]])

In [33]:
d[0,0]

0

In [34]:
d[:,0]

array([0, 2])

In [35]:
d[0,:]

array([0, 1])