# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [ ]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [8]:
import numpy as np
arraynp = np.arange(0,1000000)
lista1 = range(0,1000000)
print(arraynp)

[     0      1      2 ... 999997 999998 999999]


In [11]:
list_dobro = [x*2 for x in lista1]

In [13]:
import time

inicio = time.time()
arraynp*2
fim = time.time()
print(fim - inicio)

0.003998756408691406


In [14]:
inicio = time.time()
[x*2 for x in lista1]
fim = time.time()
print(fim - inicio)

0.15391087532043457


In [101]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 31 ms
Wall time: 1.08 s


### Exercício 2

In [ ]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [105]:
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
array1[5:8]=0

In [107]:
array1

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [ ]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

In [22]:
array2 = np.matrix([[1,2,3],[10,20,30],[100,200,300]])

In [23]:
array2

matrix([[  1,   2,   3],
        [ 10,  20,  30],
        [100, 200, 300]])

In [26]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [108]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [113]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [27]:
array2 = np.matrix([[1,2,3],[10,20,30],[100,200,300]])

In [28]:
array2

matrix([[  1,   2,   3],
        [ 10,  20,  30],
        [100, 200, 300]])

In [119]:
# Imprima os elementos da terceira linha da matriz
print(array2[2])

# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
print(array2[:2, 1:])

#ou

print(array2[0:2, 1:3])

[[100 200 300]]
[[ 2  3]
 [20 30]]
[[ 2  3]
 [20 30]]


### Exercício 5

In [40]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
np.transpose(arr)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [120]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [42]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [51]:
narray = np.zeros(len(cond))
narray

np.append

array([0., 0., 0., 0., 0.])

In [55]:
for x in range(0,len(cond)):
    if cond[x] == True:
        narray[x] = xarr[x]
    else:
        narray[x] = yarr[x]
narray

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [121]:
for x, y, c in zip(xarr, yarr, cond):
    print(x, y, c)

resultado = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
resultado

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [ ]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

In [122]:
A = np.array(range(0,10))
print(A)

np.save('minhamatriz', A)

[0 1 2 3 4 5 6 7 8 9]


In [123]:
B = np.load('minhamatriz.npy')
print(B)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [61]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [62]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [124]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [125]:
data = resp.json()
data[0]['title']

'DOC: add documentation for read_spss(#27476)'

In [126]:
df = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
df

number                                              title  \
0    27594       DOC: add documentation for read_spss(#27476)   
1    27593       User reports numerical errors in rolling std   
2    27591  BUG: MultiIndex Slice returns incorrect slice ...   
3    27589                                    Add NumPy Stubs   
4    27586                Move json_normalize to pd namespace   
5    27585             Index._engine creates cyclig reference   
6    27584                 CLN: Centralised _check_percentile   
7    27583  Inconsistent dtype changes between multi-colum...   
8    27582            merge_asof parameters "index", "prefix"   
9    27581                   Add a new DataFrame.dti accessor   
10   27580             DOC:Update python version support info   
11   27578  `groupby().first()` docs should explain distin...   
12   27576               CLN: Prune unnecessary indexing code   
13   27573  Make most arguments for read_html and read_jso...   
14   27571                   BUG: dir(IntervalIndex()) raises   
15   27570  BUG: Grouper.cov emits warning unlike DataFram...   
16   27569                                CLN: update comment   
17   27568                Enable --check-untyped-def for MyPy   
18   27567                   CLN: remove block._coerce_values   
19   27563  Pandas - Repeat headings every n-th row in Jup...   
20   27562  DOC: Harmonize column selection to bracket not...   
21   27559                 CLN: centrailize _check_percentile   
22   27558       DOC: Unable to import pandas on python 3.5.2   
23   27557  Adhere to the standard for dropping Python ver...   
24   27554                                        why not xml   
25   27553  `OptionError` raised by top-level function `pa...   
26   27552  STY: add pandas._typing to the known_pre_core ...   
27   27547            read.sql fails with adodbapi connection   
28   27544            use keyword only args where appropriate   
29   27539       Dataframe construction from numba typed list   

                                               labels state  
0                                                  []  open  
1                                                  []  open  
2                                                  []  open  
3   [{'id': 527603109, 'node_id': 'MDU6TGFiZWw1Mjc...  open  
4   [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
5                                                  []  open  
6   [{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
7   [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open  
8                                                  []  open  
9                                                  []  open  
10  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
11  [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
12  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
13  [{'id': 57395487, 'node_id': 'MDU6TGFiZWw1NzM5...  open  
14  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
15                                                 []  open  
16                                                 []  open  
17  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
18                                                 []  open  
19  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
20  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
21  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
22  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
23  [{'id': 49747336, 'node_id': 'MDU6TGFiZWw0OTc0...  open  
24                                                 []  open  
25  [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
26  [{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...  open  
27  [{'id': 47232590, 'node_id': 'MDU6TGFiZWw0NzIz...  open  
28  [{'id': 49747336, 'node_id': 'MDU6TGFiZWw0OTc0...  open  
29  [{'id': 1465286368, 'node_id': 'MDU6TGFiZWwxND...  open

### Exercício 10

In [127]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

In [128]:
# Reemove o arquivo com o banco de dados SQLite (caso exista)
import os
os.remove("exercicio.db") if os.path.exists("exercicio.db") else None

# Importando o módulo de acesso ao SQLite
import sqlite3

In [129]:
# Cria uma conexão com o banco de dados. 
# Se o banco de dados não existir, ele é criado neste momento.
con = sqlite3.connect('exercicio.db')

In [130]:
type(con)

sqlite3.Connection

In [131]:
# Criando um cursor 
# (Um cursor permite percorrer todos os registros em um conjunto de dados)
cur = con.cursor()

In [132]:
type(cur)

sqlite3.Cursor

In [133]:
# Cria uma instrução sql
sql_create = 'create table cursos '\
'(id integer primary key, '\
'titulo varchar(100), '\
'categoria varchar(140))'

In [134]:
sql_create = 'create table cursos (id integer primary key, titulo varchar(100), categoria varchar(140))'
# cria a tabela cursos contendo três colunas (separação por vírgula)
# primeira coluna de nome id, do tipo inteiro e é uma primary key (não aceita repetições)
# segunda coluna de nome titulo do tipo caracter com até 100 posições
# terceira coluna de nome categoria do tipo caracter com até 140 posições

In [135]:
# Executando a instrução sql no cursor
cur.execute(sql_create)

In [136]:
# Criando outra sentença SQL para inserir registros
sql_insert = 'insert into cursos values (?, ?, ?)'

In [137]:
# Dados
recset = [(1000, 'Ciência de Dados', 'Data Science'),
          (1001, 'Big Data Fundamentos', 'Big Data'),
          (1002, 'Python Fundamentos', 'Análise de Dados')]

In [138]:
# Inserindo os registros
for rec in recset:
    cur.execute(sql_insert, rec)

In [139]:
# Grava a transação
con.commit()

In [140]:
# Criando outra sentença SQL para selecionar registros
# select  * from ==> instrunção SQL
# cursos nome da tabela
sql_select = 'select * from cursos'

In [141]:
# Seleciona todos os registros e recupera os registros
# executado o sql_select ele vai retornar os registros
# fetchall captura os registros e salva em dados
cur.execute(sql_select)
dados = cur.fetchall()

In [142]:
# Mostra
for linha in dados:
    print ('Curso Id: %d, Título: %s, Categoria: %s \n' % linha)

Curso Id: 1000, Título: Ciência de Dados, Categoria: Data Science 

Curso Id: 1001, Título: Big Data Fundamentos, Categoria: Big Data 

Curso Id: 1002, Título: Python Fundamentos, Categoria: Análise de Dados 



In [144]:
cur.description
pd.DataFrame(dados, columns=[x[0] for x in cur.description])

id                titulo         categoria
0  1000      Ciência de Dados      Data Science
1  1001  Big Data Fundamentos          Big Data
2  1002    Python Fundamentos  Análise de Dados

In [145]:
# Fecha a conexão
cur.close()
con.close()

### Outra Opção

In [151]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
import pandas as pd
query = """
CREATE TABLE TESTE
(Cidade VARCHAR(20), 
 Estado VARCHAR(20),
 taxa REAL,        
 Impostos INTEGER
);"""
con = sqlite3.connect('dsa.db')
con.execute(query)
con.commit()

OperationalError: table TESTE already exists

In [152]:
data = [('Natal', 'Rio Grande do Norte', 1.25, 6),
        ('Recife', 'Pernambuco', 2.6, 3),
        ('Londrina', 'Paraná', 1.7, 5)]
stmt = "INSERT INTO TESTE VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [153]:
cursor = con.execute('select * from teste')
rows = cursor.fetchall()
rows

[('Natal', 'Rio Grande do Norte', 1.25, 6),
 ('Recife', 'Pernambuco', 2.6, 3),
 ('Londrina', 'Paraná', 1.7, 5),
 ('Natal', 'Rio Grande do Norte', 1.25, 6),
 ('Recife', 'Pernambuco', 2.6, 3),
 ('Londrina', 'Paraná', 1.7, 5)]

In [154]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

Cidade               Estado  taxa  Impostos
0     Natal  Rio Grande do Norte  1.25         6
1    Recife           Pernambuco  2.60         3
2  Londrina               Paraná  1.70         5
3     Natal  Rio Grande do Norte  1.25         6
4    Recife           Pernambuco  2.60         3
5  Londrina               Paraná  1.70         5

In [155]:
cursor.close()
con.close()

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>